version: '3.8'

services:
  shop-admin:
    container_name: shop-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:85"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=85
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_ADMIN_URL}/api
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - uploads_data:/app/public/uploads

volumes:
  uploads_data:
